/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'vagrant' at '21/07/16 09:07' with Gradle 2.3
 *
 * @author vagrant, @date 21/07/16 09:07
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
